services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ft_matcha
    ports:
      - 5432:5432

  backend:
    image: backend:latest
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - ft_matcha
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend
    ports:
      - 5000:5000
      - 3333:3333

  frontend:
    image: frontend
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - ft_matcha
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000

volumes:
  db_data:
    name: db_data

networks:
  ft_matcha:
    driver: bridge
